config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :home

  get 'home' => 'home#index'
  get 'home/:id' => 'home#show'
  get 'home/new' => 'home#new'
  post 'users/new' => 'users#create'
  get 'users/:id/edit' => 'users#edit'
  post 'users/:id' => 'users#edit'
  put 'home/:id' => 'home#update'
  patch '/home/:id' => 'home#update'
  delete 'home/:id' => 'home#destroy'
  

end

app/models/post.rb
#not being used yet

class Post < ActiveRecord::Base
	validates :content, :length => { :maximum => 140 }
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
# ======== INDEX OF POSTS ======== #
	def index
		@users = User.all
		if @users.present?
			flash[:notice] = "Here's your list of users"
		else
			flash[:alert] = "No users saved"
		end	 
	end

	# ======== DISPLAYS POST BY ID ======== #
	def show
		@user = User.find(params[:id])
	end

	# ======== 'GET' PAGE SHOWING THE CREATE POST PAGE ======== #
	def new
		@user = User.new
	end

	# ======== 'POST' PAGE TO CREATE A NEW POST ======== #
	def create 
		@user = User.create(params.require(:user).permit(:fname, :lname, :email, :password))
		redirect_to home_create_path
	end

	# ======== 'GET' PAGE TO UPDATE POST INFO ======== #
	def edit
		@user = User.find(params[:id])
	end

	# ======== 'PUT' PAGE TO UPDATE (REPLACE) POST INFO ======== #
	def update
		@user = User.find(params[:id])
		@user = User.update.require(:user).permit(:fname, :lname, :email, :password)
		redirect_to home_index_path
	end

	# ======== SEEK & DESTROY ======== #
	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to home_index_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
# ======== INDEX OF POSTS ======== #
	def index
		@users = User.all
		if @users.present?
			flash[:notice] = "Here's your list of users"
		else
			flash[:alert] = "No users saved"
		end	 
	end

	# ======== DISPLAYS POST BY ID ======== #
	def show
		@user = User.find(params[:id])
	end

	# ======== 'GET' PAGE SHOWING THE CREATE POST PAGE ======== #
	def new
		@user = User.new
	end

	# ======== 'POST' PAGE TO CREATE A NEW POST ======== #
	def create 
		@user = User.create(params.require(:user).permit(:fname, :lname, :email, :password))
		flash[:done] = "New user created"
		redirect_to home_index_path
	end

	# ======== 'GET' PAGE TO UPDATE POST INFO ======== #
	def edit
		@user = User.find(params[:id])
	end

	# ======== 'PUT' PAGE TO UPDATE (REPLACE) POST INFO ======== #
	def update
		@user = User.find(params[:id])
		@user.update(params.require(:user).permit(:fname, :lname, :email, :password))
		flash[:success] = "Account updated"
		redirect_to home_index_path
	end

	# ======== SEEK & DESTROY ======== #
	def destroy
		@user = User.find(params[:id])
		@user.destroy
		flash[:destroyed] = "User deleted"
		redirect_to home_index_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/edit.html.erb
<h1>Update User</h1>

<%= form_for @user do |f| %>
	<%= f.label "First Name" %>
	<%= f.text_field :fname %>
	<%= f.label "Last Name" %>
	<%= f.text_field :lname %>
	<%= f.label "E-mail" %>
	<%= f.text_field :email %>
	<%= f.label "Password" %>
	<%= f.text_field :password %>
	<%= f.submit :update %>
<% end %>

app/views/home/index.html.erb
<h1>USER INDEX</h1>


<h3><%= flash[:notice] if flash[:notice] %></h3>
<h3><%= flash[:alert] if flash[:alert] %></h3>
<h3><%= flash[:success] if flash[:success] %></h3>
<h3><%= flash[:done] if flash[:done] %></h3>
<h3><%= flash[:destroyed] if flash[:destroyed] %></h3>

<h2><%= link_to 'New User', home_new_path%></h2>

<% @users.each do |user| %>
	<ul>
		<li><%= user.fname %></li>
		<li><%= user.lname %></li>
		<li><%= user.email %></li>
		<%= link_to 'Edit', user, method: :edit %>
		<%= link_to 'Delete', user, method: :delete, data: { confirm: "You sure?" }%>
	</ul>
<% end %>

app/views/home/new.html.erb
<%= form_for (@user) do |f| %>   
	<%=f.label :fname %>   
	<%=f.text_field :fname %>  
	 <%=f.submit :create %> 
<% end %>

app/views/home/show.html.erb
<h1>USER INFO</h1>

<ul>
	<li><%= @user.fname %></li>
	<li><%= @user.lname %></li>
	<li><%= @user.email %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Part1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<h1>Update User</h1>

<%= form_for @user do |f| %>
	<%= f.label "First Name" %>
	<%= f.text_field :fname %>
	<%= f.label "Last Name" %>
	<%= f.text_field :lname %>
	<%= f.label "E-mail" %>
	<%= f.text_field :email %>
	<%= f.label "Password" %>
	<%= f.text_field :password %>
	<%= f.submit :update %>
	<br>
	<br>
	<%= link_to 'Go Back', home_index_path%>
<% end %>